gameapp/urls.py
from django.urls import path,re_path
from django.conf.urls import url
from gameapp import views

app_name ='gameapp'
urlpatterns=[
    path('',views.home,name='home'),
    path('game/',views.game,name='game'),
    path('scrape/',views.scrape,name='scraper'),
    path('actualgame/',views.actualgame,name='actualgame'),
    re_path(r'^quotes/(?P<author>[\w|\W]+)/$',views.quotesbyauthor,name='authorquotes'),
]

guessgame/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),  
    path('',include('gameapp.urls')),
]

gameapp/models.py
from django.db import models

# Create your models here.

class Quotes(models.Model):

    def __str__(self):
        return f'Quote {self.author}'

    author = models.CharField(max_length=500)
    text = models.CharField(max_length=4000)
    biolink = models.CharField(max_length=500)
    author_born = models.CharField(max_length=1000)
    author_location = models.CharField(max_length=1000)

gameapp/forms.py
from django import forms

class AnswerValid(forms.Form):
    user_answer = forms.CharField(max_length=100)
    

gameapp/views.py
from django.shortcuts import render,redirect
from django.http import JsonResponse, Http404
import requests
from bs4 import BeautifulSoup
from .models import Quotes
from random import choice
from .forms import AnswerValid

BASE_URL = "http://quotes.toscrape.com"
REMAINING_GUESSES = 4

# Create your views here.

def home(request):
    try:
        authors = Quotes.objects.values('author').distinct()
        data = {'authors':authors}
        return render(request,'gameapp/home.html',context = data)
    except:
        raise Http404


def scrape(request):
    url = '/page/1'
    while url:
        response = requests.get(f'{BASE_URL}{url}')
        print(f"Now Scraping {BASE_URL}{url}...")
        soup = BeautifulSoup(response.text,'html.parser')
        quotes = soup.find_all(class_='quote')

        for quote in quotes:
            name = quote.find('small').get_text()
            text = quote.find(class_='text').get_text()
            link = quote.find('a')['href']
            bioresponse = requests.get(f"{BASE_URL}{link}")
            print(f"Now Scraping {BASE_URL}{link}...")
            biosoup = BeautifulSoup(bioresponse.text,'html.parser')
            born = biosoup.find(class_="author-born-date").get_text()
            location = biosoup.find(class_="author-born-location").get_text()
            Quotes.objects.create(author = name, text = text, biolink = link, author_born = born, author_location = location)

        nextbtn = soup.find(class_='next')
        url = nextbtn.find('a')['href'] if nextbtn else None
    
    data = {
        'scraped' : True,
        'message' : 'Web Scraping has been completed with latest updates. U can now play game'
    }
    return render(request,'gameapp/home.html',context=data)   


def game(request):
    quotes = Quotes.objects.all()
    rand_quote_info = choice(quotes)
    request.session['quote'] = rand_quote_info.text
    request.session['author'] = rand_quote_info.author
    request.session['link'] = rand_quote_info.biolink
    request.session['born'] = rand_quote_info.author_born
    request.session['location'] = rand_quote_info.author_location
    return redirect('gameapp:actualgame')

def actualgame(request):
    quote = request.session['quote']
    author = request.session['author']
    # link = request.session['link']
    author_born_date = request.session['born']
    author_born_location = request.session['location']

    global REMAINING_GUESSES
    answer = ''

    if REMAINING_GUESSES == 0 or REMAINING_GUESSES == -1:
        REMAINING_GUESSES = 4

    while answer != author and REMAINING_GUESSES >= 0:
        if request.method == 'POST':
            if request.is_ajax():
                form = AnswerValid(request.POST)
                if form.is_valid():
                    answer = form.cleaned_data.get('user_answer')
                    REMAINING_GUESSES -= 1
                    print(REMAINING_GUESSES)

                    if answer == author:
                        REMAINING_GUESSES=4
                        data = {
                            'ans' : 'Correct Answer',
                            'rem' : 'Ur guess was right.. Hats off!',
                            'hint' : 'Be happy.. ur answer was right... Click on Play again for try again'
                        }
                        return JsonResponse(data)

                    elif REMAINING_GUESSES == 3 and answer.lower() != author.lower():
                        data = {
                            'ans' : 'Let me give u one hint..',
                            'rem' : REMAINING_GUESSES,
                            'hint' : f'That person was born on {author_born_date} {author_born_location}'
                        }
                        print(author,author_born_date,author_born_location)
                        print(f'remaining guesses:{REMAINING_GUESSES}')
                        return JsonResponse(data)

                    elif REMAINING_GUESSES == 2 and answer.lower() != author.lower():
                        data = {
                            'ans' : 'One hint wasted.. No worries. One more hint',
                            'rem' : REMAINING_GUESSES,
                            'hint' : f'Name starts with {author[0]}'
                        }
                        print(f'remaining guesses:{REMAINING_GUESSES}')
                        return JsonResponse(data)

                    elif REMAINING_GUESSES == 1 and answer.lower() != author.lower():
                        last_name_initial = author.split(' ')[1][0]
                        data = {
                            'ans' : 'Oh no this is the last hint. Answer or ur life is finished..',
                            'rem' : REMAINING_GUESSES,
                            'hint' : f'Name ends with {last_name_initial}'
                        }
                        print(f'remaining guesses:{REMAINING_GUESSES}')
                        return JsonResponse(data)

                    elif REMAINING_GUESSES == 0 and answer.lower() != author.lower():
                        data = {
                            'ans' : f'U lost the game... The correct answer is {author}',
                            'rem' : REMAINING_GUESSES,
                            'hint' : 'Now no hint.. u lost the match.. click on Play Again if want to try once more'
                        }
                        return JsonResponse(data)
                else:
                    print(form.errors)
                    data = {
                        'error' : True,
                        'data' : form.errors
                    }
                    return JsonResponse(data)
            else:
                error = {
                    'message': 'Error, must be an Ajax call.'
                }
                return JsonResponse(error,content_type='application/json')
        else:
            form = AnswerValid()
            data = {
                'quote':quote,
            }
            return render(request,'gameapp/game.html',context=data)


def quotesbyauthor(request,author):
    try:
        authorQS = Quotes.objects.filter(author = author)
        data = {
            'author':author,
            'quotes':authorQS
        }
        return render(request,'gameapp/authorquotes.html',context=data)

    except NameError:
        print('Enter valid author names')

gameapp/templates/gameapp/authorquotes.html
{% extends 'gameapp/base.html' %} 

{% block content %}
    <div>
        <h5>These are the famous quotes by {{ author }} :--</h5>
        {% for quote in quotes %}
        <div>
            <ul>
                <li>{{ quote.text }}</li>
            </ul>
        </div>
        {% endfor %}
    </div>
{% endblock content %}

gameapp/templates/gameapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Jijo's App</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    {% block style %}
    {% endblock style %}
</head>

<body>
    <nav class="navbar navbar-default navbar-expand-sm bg-dark" >
        <div style="width:90%">
            <a href="{% url 'gameapp:home' %}" class="navbar-brand"><img src = "{% static 'mygameapp/images/favicon.png' %}" height='30px'></a>
        </div>
        <a href="{%url 'gameapp:game' %}" >
            <button type="button" class="btn btn-light navbar-btn">Play Again</button>
         </a>     
    </nav>
    {% block content %}
    {% endblock content %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    {% block javascript %}
    {% endblock javascript %}
</body>

</html>

gameapp/templates/gameapp/game.html
{% extends 'gameapp/base.html' %}

{% block content %}
    <h5>One random quote..... Guess who said it..... U will be given only 4 attempts !!</h5>
    <p><i>{{ quote }}</i></p>
    <h5 id='guess_statement'></h5>
<form id='user_form' method='POST' action=''>
    {% csrf_token %}
    <h6>
        <label for="id_user_answer">User Answer:</label>
        <input type="text" name="user_answer" maxlength="100" required id="id_user_answer" style="height:30px">
        <button type = "submit" class="btn btn-sm btn-dark">Guess</button>
    </h6>
</form><br>
<h5 id='ans'></h5>
<ul id='hint'></ul>
{% endblock content %}

{% block javascript %}
<script>
    $("#user_form").submit(function(e){
        console.log("Submitting the form");
        e.preventDefault();
        //get the form data
        var formdata = {
            'user_answer':$('#id_user_answer').val(),
            csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
            contentType: 'application/x-www-form-urlencoded',
            encode: true,
        };
        // console.log(formdata)
        $.ajax({
            type: 'POST',
            url: '{% url "gameapp:actualgame" %}',
            data: formdata,
            dataType: 'json',
        }).done(function (data) {
            // console.log(data);
            $(function() {
                $('#ans').text(data['ans']);
                $('#guess_statement').html('<h5>Guesses remaining: '+data['rem']+'</h5>');
                $('#hint').append('<li>'+data['hint']+'</li>');
            });
        });
    });
</script>
{% endblock javascript %}

gameapp/templates/gameapp/home.html
{% extends 'gameapp/base.html' %}

{% block content %}
    <h4>What would u like to do?
        <span><a href={%url 'gameapp:scraper' %} class="btn btn-md btn-primary disabled"><i>Scrape</i></a></span>
        <span><a href={%url 'gameapp:game' %} class="btn btn-md btn-primary"><i>Play</i></a></span>
    </h4>

    {% if scraped %}
        <p>{{ message }}</p>
    {% endif %}

    <div>
        <h5>Some Authors:</h5>
        {% for i in authors %}
                <a href={% url 'gameapp:authorquotes' author=i.author %}>
                    <span class="border border-light">{{ i.author }}</span>
                </a>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   
        {% endfor %}
    </div> 
{% endblock content %}